// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Cancels an order.
//
//   - If the status is `PENDING_PAYMENT`, changes it to `CANCELLED`.
//   - If the status is `PAID`, returns 409 Conflict.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Creates a new order based on the parts selected by the user.
//
//   - Fetches parts via `InventoryService.ListParts`.
//   - Verifies that all parts exist. If at least one is missing, returns an error.
//   - Calculates `total_price` and generates `order_uuid`.
//   - Saves the order with status `PENDING_PAYMENT`.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUuid implements GetOrderByUuid operation.
//
// Looks up the order by UUID and returns it, or 404 Not Found.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (r GetOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Processes payment for a previously created order.
//
//   - Finds the order by `order_uuid`. If it does not exist, returns 404 Not Found.
//   - Calls `PaymentService.PayOrder` with `user_uuid`, `order_uuid` and `payment_method` and receives
//     `transaction_uuid`.
//   - Updates the order: status -> `PAID`, stores `transaction_uuid` and `payment_method`.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *UnexpectedErrorStatusCode) {
	r = new(UnexpectedErrorStatusCode)
	return r
}
