// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Cancels an order.
	//
	//  - If the status is `PENDING_PAYMENT`, changes it to `CANCELLED`.
	//  - If the status is `PAID`, returns 409 Conflict.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Creates a new order based on the parts selected by the user.
	//
	//  - Fetches parts via `InventoryService.ListParts`.
	//  - Verifies that all parts exist. If at least one is missing, returns an error.
	//  - Calculates `total_price` and generates `order_uuid`.
	//  - Saves the order with status `PENDING_PAYMENT`.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUuid implements GetOrderByUuid operation.
	//
	// Looks up the order by UUID and returns it, or 404 Not Found.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (GetOrderByUuidRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Processes payment for a previously created order.
	//
	//  - Finds the order by `order_uuid`. If it does not exist, returns 404 Not Found.
	//  - Calls `PaymentService.PayOrder` with `user_uuid`, `order_uuid` and `payment_method` and receives
	//    `transaction_uuid`.
	//  - Updates the order: status -> `PAID`, stores `transaction_uuid` and `payment_method`.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *UnexpectedErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
